run:
  timeout: 10m
  go: '1.20'
linters:
  enable:
    - revive
    - gofmt
    - goconst
    - tagliatelle
    - whitespace
    - gosec
    - gocritic
    - misspell
    - errcheck
    - errorlint
    - unused
    - staticcheck
    # - wrapcheck
  presets:
    - format
  disable:
    - gofumpt
    - gci
