name: Conformance Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '>=1.20.4'

      - run: go mod download

      - run: go build -o conformance cmd/conformance/main.go

      - uses: sigstore/sigstore-conformance@064fb32a890c30235f305281f3509c5e65e6f9e5 # v0.0.4
        with:
          entrypoint: conformance
