name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://goproxy.githubapp.com/mod,https://proxy.golang.org/,direct
      GOPRIVATE: ''
      GONOPROXY: ''
      GONOSUMDB: github.com/github/*
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Configure Go private module access
        run: |
          echo "machine goproxy.githubapp.com login nobody password ${{ secrets.GOPROXY_TOKEN }}" >> $HOME/.netrc
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose
          # sometimes the pkg cache gets corrupted, skipping cache avoids this
          # https://github.com/golangci/golangci-lint-action/issues/23
          skip-pkg-cache: true
